/*
 * BCDSevSegment_cfg.h
 *
 * Created: 2/18/2019 1:37:11 PM
 *  Author: AVE-LAP-040
 */ 


#ifndef BCDSEVSEGMENT_CFG_H_
#define BCDSEVSEGMENT_CFG_H_


#define BCDSEVSEGMENTS1_Enable_PIN PIN26
#define BCDSEVSEGMENTS2_Enable_PIN PIN27
#define BCDSEVSEGMENTS3_Enable_PIN PIN30
#define BCDSEVSEGMENTS4_Enable_PIN PIN31

#define BCDSEVSEGMENTS1_DATA_PIN PIN8
#define BCDSEVSEGMENTS2_DATA_PIN PIN9
#define BCDSEVSEGMENTS3_DATA_PIN PIN10
#define BCDSEVSEGMENTS4_DATA_PIN PIN11


#endif /* BCDSEVSEGMENT_CFG_H_ */